### ISSUE TITLE
Problem with Flashing

### ISSUE THREAD

**Issue by explit28** [yeokm1/graphics-gremlin-hdmi#4]
Hello @yeokm1 - Sorry for opening issue in your Repo and not in the TubeTime Repo, maybe you can answer my question.
Its about original GG. Your GG HDMI is in Production, so i dont tried it yet. 

I flash with a little bit different UM-FT2232H Module, because its much cheaper in Germany.
The Problem which i have are the missing 3 Pins 
V3V3 to VIO strap
VBUS to VCC strap
V3V3 to VIO strap (2)
which are not there on my UM-FT2232H Module

I already posted a question in the original GG Repo:
https://github.com/schlae/graphics-gremlin/issues/22

To my Problem:

I could flash 2 cards without this 3 PINs - anything was fine.
Now, it flashes without errors, but at the End i get a Message that Flash and File are different.
When i try the card - it doesn't work. Somehow the Flash ROM is messed.

Maybe you have some Ideas with:

- what to do with 3 missing pins
- how to solve the flashing problem
- ![335827819-821b1da9-bf12-4a01-b264-e9248e67e71e](https://github.com/yeokm1/graphics-gremlin-hdmi/assets/11852348/d8d64e67-bdae-4170-b2d3-ae545e22c542)
![photo_2024-06-09_19-06-23](https://github.com/yeokm1/graphics-gremlin-hdmi/assets/11852348/20a16384-4032-4f15-8013-d84554f24cd4)
![photo_2024-06-09_19-06-23 (2)](https://github.com/yeokm1/graphics-gremlin-hdmi/assets/11852348/d54d5d44-895f-4b66-b27b-ba01329be66c)

Thank you very much!

**Comment by yeokm1** [comment]
May I ask if you have powered on the card in addition to connecting the programming header?

For the original GG, you have to power the card via a PC with an ISA slot. For the GG HDMI, using a PC for power is not mandatory as I added 5V supply header which you can power the card from.

Without power to the GG card, the FT2232 will just blindly write to SPI output but you will find problems reading back the flash.

Perhaps you can take a photo of your flashing setup including the GG?

I'm not familiar with UM-FT2232H Module. 

- VBUS to VCC supplies power to the voltage regulators that supplies to FT2232.

- V3V3 to VIO strap and V3V3 to VIO strap (2) is just to supply power to the FT2232's input/output section. 

If the UM-FT2232H module has strapped them all internally for you, then you don't have to do anything.

**Comment by explit28** [comment]
Thank you very much for fast answer, @yeokm1 !
Of course i flash the card, when its in my Micro8088 PC and the PC is on. Otherwise it would not get 5V over ISA.
As i said, the first 2 times i flashed without no Problems.
I am afraid, that i somehow programmed the FPGA with 5V instead of 3.3V and now the flash is corrupted.

I think the best idea would be to buy the real FT2232 and try it again...

Another question: Do you plan make your software improvements for the GG HDMI also available for the normal GG?
Thanks

**Comment by yeokm1** [comment]
It is indeed true that the FPGA and flash memory are not 5V tolerant. If you somehow use 5V to do so, then yes something could be damaged. Another thing could be ESD.

This video might be interesting for you. He suggests an alternative (in comments) to use Adafruit FT232H breakout board to avoid flashing software problems. https://www.youtube.com/watch?v=ywzjZvqpQcI

One way to help troubleshoot the issue is to see if you can read out the flash serial number. Go to 09:10 of his video.

If all else fails, then no choice but to get the original FT2232 mini module and try it.

The logic changes I have made to the GG HDMI are strictly to support the HDMI section. Not transferable to the original GG.

**Comment by explit28** [comment]
I close the issue, it was a problem with my wiring. some of the cables has bad connection. Thanks for Help!
